version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html   # React build folder
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro   # Optional custom config
